trigger:
- main

pool:
  vmImage: ubuntu-latest
variables:
- group: 'RecycleAppPool'
- name: IIS Server
  value: "xyz"
steps:
- task: IISWebAppManagementOnMachineGroup@0
  inputs:
    IISDeploymentType: 'IISApplicationPool'
    ActionIISApplicationPool: 'RecycleAppPool'
    StartStopRecycleAppPoolName: 'IVR-Services'

 