trigger:
- main

pool:
  vmImage: ubuntu-latest
variables:
 targetDirectory: 'C:\Users\ASUA\Documents\Delete files'
 filePattern: '*.xlsx'
steps:
- checkout: self

- task: PowerShell@2
  inputs:
    targetType: filePath
    filePath: '$(System.DefaultWorkingDirectory)/Deletefiles.ps1'
    arguments: '-targetDirectory $(targetDirectory) -filePattern $(filePattern)'
    pwsh: true


- script: |
   
